import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/constants";

/**
 * Sitemap index — points to one sitemap per country market.
 * Each market's sitemap is generated by its own route.ts (sitemap-{code}.xml).
 */
export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: `${SITE_URL}/sitemap-in.xml`, lastModified: new Date() },
    { url: `${SITE_URL}/sitemap-gb.xml`, lastModified: new Date() },
    { url: `${SITE_URL}/sitemap-sg.xml`, lastModified: new Date() },
  ];
}
