import React from "react";
import {
  FlagUS,
  FlagSG,
  FlagGB,
  FlagIN,
  FlagAU,
  FlagCA,
  FlagMX,
  FlagIE,
  FlagFR,
  FlagDE,
  FlagES,
  FlagIT,
  FlagNL,
  FlagBE,
  FlagSE,
  FlagNO,
  FlagDK,
  FlagFI,
  FlagRU,
  FlagPL,
  FlagCZ,
  FlagAT,
  FlagCH,
  FlagPT,
  FlagGR,
  FlagTR,
  FlagIL,
  FlagSA,
  FlagAE,
  FlagEG,
  FlagNG,
  FlagZA,
  FlagKE,
  FlagPK,
  FlagBD,
  FlagLK,
  FlagJP,
  FlagKR,
  FlagCN,
  FlagTW,
  FlagHK,
  FlagNZ,
  FlagBR,
  FlagAR,
  FlagCL,
  FlagCO,
  FlagPE,
  FlagVE,
  FlagAuto,
} from "./flags";

export type Country = {
  code: string; // ISO2
  name: string;
  dial: string; // without +
  Flag: React.FC<React.SVGProps<SVGSVGElement>>;
};

export const COUNTRIES: Country[] = [
  { code: "US", name: "United States", dial: "1", Flag: FlagUS },
  { code: "CA", name: "Canada", dial: "1", Flag: FlagCA },
  { code: "MX", name: "Mexico", dial: "52", Flag: FlagMX },
  { code: "GB", name: "United Kingdom", dial: "44", Flag: FlagGB },
  { code: "IE", name: "Ireland", dial: "353", Flag: FlagIE },
  { code: "FR", name: "France", dial: "33", Flag: FlagFR },
  { code: "DE", name: "Germany", dial: "49", Flag: FlagDE },
  { code: "ES", name: "Spain", dial: "34", Flag: FlagES },
  { code: "IT", name: "Italy", dial: "39", Flag: FlagIT },
  { code: "NL", name: "Netherlands", dial: "31", Flag: FlagNL },
  { code: "BE", name: "Belgium", dial: "32", Flag: FlagBE },
  { code: "SE", name: "Sweden", dial: "46", Flag: FlagSE },
  { code: "NO", name: "Norway", dial: "47", Flag: FlagNO },
  { code: "DK", name: "Denmark", dial: "45", Flag: FlagDK },
  { code: "FI", name: "Finland", dial: "358", Flag: FlagFI },
  { code: "RU", name: "Russia", dial: "7", Flag: FlagRU },
  { code: "PL", name: "Poland", dial: "48", Flag: FlagPL },
  { code: "CZ", name: "Czechia", dial: "420", Flag: FlagCZ },
  { code: "AT", name: "Austria", dial: "43", Flag: FlagAT },
  { code: "CH", name: "Switzerland", dial: "41", Flag: FlagCH },
  { code: "PT", name: "Portugal", dial: "351", Flag: FlagPT },
  { code: "GR", name: "Greece", dial: "30", Flag: FlagGR },
  { code: "TR", name: "Turkey", dial: "90", Flag: FlagTR },
  { code: "IL", name: "Israel", dial: "972", Flag: FlagIL },
  { code: "SA", name: "Saudi Arabia", dial: "966", Flag: FlagSA },
  { code: "AE", name: "United Arab Emirates", dial: "971", Flag: FlagAE },
  { code: "EG", name: "Egypt", dial: "20", Flag: FlagEG },
  { code: "NG", name: "Nigeria", dial: "234", Flag: FlagNG },
  { code: "ZA", name: "South Africa", dial: "27", Flag: FlagZA },
  { code: "KE", name: "Kenya", dial: "254", Flag: FlagKE },
  { code: "IN", name: "India", dial: "91", Flag: FlagIN },
  { code: "PK", name: "Pakistan", dial: "92", Flag: FlagPK },
  { code: "BD", name: "Bangladesh", dial: "880", Flag: FlagBD },
  { code: "LK", name: "Sri Lanka", dial: "94", Flag: FlagLK },
  { code: "JP", name: "Japan", dial: "81", Flag: FlagJP },
  { code: "KR", name: "South Korea", dial: "82", Flag: FlagKR },
  { code: "CN", name: "China", dial: "86", Flag: FlagCN },
  { code: "TW", name: "Taiwan", dial: "886", Flag: FlagTW },
  { code: "HK", name: "Hong Kong", dial: "852", Flag: FlagHK },
  { code: "SG", name: "Singapore", dial: "65", Flag: FlagSG },
  { code: "AU", name: "Australia", dial: "61", Flag: FlagAU },
  { code: "NZ", name: "New Zealand", dial: "64", Flag: FlagNZ },
  { code: "BR", name: "Brazil", dial: "55", Flag: FlagBR },
  { code: "AR", name: "Argentina", dial: "54", Flag: FlagAR },
  { code: "CL", name: "Chile", dial: "56", Flag: FlagCL },
  { code: "CO", name: "Colombia", dial: "57", Flag: FlagCO },
  { code: "PE", name: "Peru", dial: "51", Flag: FlagPE },
  { code: "VE", name: "Venezuela", dial: "58", Flag: FlagVE },
] ;

export default COUNTRIES;
