import type { MainCategory } from "../types";
import { field, workArrangement, conditionFull } from "./shared";

export const business: MainCategory = {
  id: "business",
  label: "Business",
  description: "Promote, buy or sell businesses and franchises.",
  icon: "trending-up",
  iconBg: "bg-indigo-100",
  iconColor: "text-indigo-600",
  subcategories: [
    {
      id: "biz_for_sale",
      label: "Business For Sale / Lease",
      icon: "store",
      filters: [
        {
          id: "biz_action",
          label: "Action",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "For Sale",  value: "sale"  },
            { label: "For Lease", value: "lease" },
          ],
        },
        {
          id: "biz_type",
          label: "Business Type",
          type: "toggle",
          options: [
            { label: "F&B",           value: "fnb"           },
            { label: "Retail",        value: "retail"        },
            { label: "E-commerce",    value: "ecommerce"     },
            { label: "Services",      value: "services"      },
            { label: "Manufacturing", value: "manufacturing"  },
            { label: "Healthcare",    value: "healthcare"    },
            { label: "Education",     value: "education"     },
            { label: "Tech",          value: "tech"          },
            { label: "Other",         value: "other"         },
          ],
        },
        {
          id: "annual_revenue",
          label: "Annual Revenue",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Pre-revenue", value: "pre"    },
            { label: "< 100k",      value: "sub100" },
            { label: "100k – 500k", value: "500k"   },
            { label: "500k – 1M",   value: "1m"     },
            { label: "1M+",         value: "1mup"   },
          ],
        },
        {
          id: "staff_size",
          label: "Staff Size",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Solo",  value: "solo"   },
            { label: "1-5",   value: "1to5"   },
            { label: "6-20",  value: "6to20"  },
            { label: "21-50", value: "21to50" },
            { label: "50+",   value: "50up"   },
          ],
        },
      ],
    },
    {
      id: "b2b_service",
      label: "B2B Service",
      icon: "briefcase",
      filters: [
        {
          id: "service_type",
          label: "Service",
          type: "toggle",
          options: [
            { label: "IT & Tech",        value: "it"         },
            { label: "Legal",            value: "legal"      },
            { label: "Accounting",       value: "accounting" },
            { label: "Marketing",        value: "marketing"  },
            { label: "Logistics",        value: "logistics"  },
            { label: "HR & Recruitment", value: "hr"         },
            { label: "Security",         value: "security"   },
            { label: "Consulting",       value: "consulting" },
            { label: "Facility Mgmt",    value: "facility"   },
            { label: "Other",            value: "other"      },
          ],
        },
        {
          id: "provider",
          label: "Provider",
          type: "toggle",
          options: [
            { label: "Individual", value: "individual" },
            { label: "Agency",     value: "agency"     },
            { label: "Company",    value: "company"    },
          ],
        },
        {
          id: "engagement",
          label: "Engagement",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "One-off",       value: "oneoff"   },
            { label: "Project-based", value: "project"  },
            { label: "Retainer",      value: "retainer" },
          ],
        },
      ],
    },
    {
      id: "freelance_contractors",
      label: "Freelance / Contractors",
      icon: "user-check",
      filters: [
        field,
        {
          id: "engagement",
          label: "Engagement",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "One-off",  value: "oneoff"  },
            { label: "Project",  value: "project" },
            { label: "Ongoing",  value: "ongoing" },
          ],
        },
        workArrangement,
      ],
    },
    {
      id: "partnership",
      label: "Partnership Opportunities",
      icon: "handshake",
      filters: [
        {
          id: "partner_type",
          label: "Looking For",
          type: "toggle",
          options: [
            { label: "Co-founder",        value: "cofounder"   },
            { label: "Investor",          value: "investor"    },
            { label: "Strategic Partner", value: "strategic"   },
            { label: "Distributor",       value: "distributor" },
            { label: "Reseller",          value: "reseller"    },
            { label: "Joint Venture",     value: "jv"          },
          ],
        },
        {
          id: "industry",
          label: "Industry",
          type: "toggle",
          options: [
            { label: "Tech",          value: "tech"          },
            { label: "F&B",           value: "fnb"           },
            { label: "Retail",        value: "retail"        },
            { label: "Services",      value: "services"      },
            { label: "Manufacturing", value: "manufacturing"  },
            { label: "Healthcare",    value: "healthcare"    },
            { label: "Education",     value: "education"     },
            { label: "Finance",       value: "finance"       },
            { label: "Other",         value: "other"         },
          ],
        },
        {
          id: "biz_stage",
          label: "Stage",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Idea Stage",    value: "idea"        },
            { label: "MVP",           value: "mvp"         },
            { label: "Early Revenue", value: "early"       },
            { label: "Established",   value: "established" },
          ],
        },
      ],
    },
    {
      id: "equipment_supplies",
      label: "Equipment & Supplies",
      icon: "wrench",
      filters: [
        {
          id: "equip_action",
          label: "Action",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "For Sale", value: "sale"   },
            { label: "For Rent", value: "rent"   },
            { label: "Wanted",   value: "wanted" },
          ],
        },
        {
          id: "equip_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Industrial",    value: "industrial"   },
            { label: "Office",        value: "office"       },
            { label: "Kitchen & F&B", value: "kitchen"      },
            { label: "Medical & Lab", value: "medical"      },
            { label: "Construction",  value: "construction" },
            { label: "IT & Tech",     value: "it"           },
            { label: "Retail",        value: "retail"       },
            { label: "Other",         value: "other"        },
          ],
        },
        conditionFull,
      ],
    },
    {
      id: "startup_support",
      label: "Startup Support",
      icon: "rocket",
      filters: [
        {
          id: "support_type",
          label: "Support",
          type: "toggle",
          options: [
            { label: "Mentoring",    value: "mentoring"   },
            { label: "Funding",      value: "funding"     },
            { label: "Incubator",    value: "incubator"   },
            { label: "Accelerator",  value: "accelerator" },
            { label: "Co-working",   value: "coworking"   },
            { label: "Legal",        value: "legal"       },
            { label: "Networking",   value: "networking"  },
            { label: "Tech Support", value: "tech"        },
          ],
        },
        {
          id: "industry",
          label: "Industry",
          type: "toggle",
          options: [
            { label: "Tech",       value: "tech"       },
            { label: "F&B",        value: "fnb"        },
            { label: "Retail",     value: "retail"     },
            { label: "Services",   value: "services"   },
            { label: "Healthcare", value: "healthcare" },
            { label: "Education",  value: "education"  },
            { label: "Other",      value: "other"      },
          ],
        },
        {
          id: "startup_stage",
          label: "Stage",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Idea",          value: "idea"   },
            { label: "MVP",           value: "mvp"    },
            { label: "Early Revenue", value: "early"  },
            { label: "Growth",        value: "growth" },
          ],
        },
      ],
    },
    {
      id: "training",
      label: "Training Opportunities",
      icon: "graduation-cap",
      filters: [
        {
          id: "training_type",
          label: "Topic",
          type: "toggle",
          options: [
            { label: "Leadership", value: "leadership" },
            { label: "Sales",      value: "sales"      },
            { label: "Marketing",  value: "marketing"  },
            { label: "Finance",    value: "finance"    },
            { label: "IT & Tech",  value: "it"         },
            { label: "HR",         value: "hr"         },
            { label: "Operations", value: "operations" },
            { label: "Compliance", value: "compliance" },
            { label: "Other",      value: "other"      },
          ],
        },
        {
          id: "format",
          label: "Format",
          type: "toggle",
          options: [
            { label: "Workshop", value: "workshop" },
            { label: "Seminar",  value: "seminar"  },
            { label: "Classroom",value: "class"    },
            { label: "Online",   value: "online"   },
            { label: "Webinar",  value: "webinar"  },
          ],
        },
        {
          id: "audience",
          label: "For",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Individual", value: "individual" },
            { label: "Team",       value: "team"       },
            { label: "Corporate",  value: "corporate"  },
          ],
        },
      ],
    },
    {
      id: "franchise",
      label: "Franchise Opportunities",
      icon: "layout-grid",
      filters: [
        {
          id: "franchise_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "F&B",        value: "fnb"        },
            { label: "Retail",     value: "retail"     },
            { label: "Education",  value: "education"  },
            { label: "Services",   value: "services"   },
            { label: "Fitness",    value: "fitness"    },
            { label: "Healthcare", value: "healthcare" },
            { label: "Beauty",     value: "beauty"     },
            { label: "Other",      value: "other"      },
          ],
        },
        {
          id: "investment_level",
          label: "Investment",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "< 50k",       value: "sub50"  },
            { label: "50k – 200k",  value: "200k"   },
            { label: "200k – 500k", value: "500k"   },
            { label: "500k+",       value: "500kup" },
          ],
        },
        {
          id: "franchise_type",
          label: "Type",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Unit Franchise",   value: "unit"   },
            { label: "Master Franchise", value: "master" },
            { label: "Area Dev",         value: "area"   },
          ],
        },
      ],
    },
    {
      id: "biz_events",
      label: "Business Events",
      icon: "calendar",
      filters: [
        {
          id: "event_type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Conference",     value: "conference" },
            { label: "Exhibition",     value: "exhibition" },
            { label: "Trade Fair",     value: "trade_fair" },
            { label: "Networking",     value: "networking" },
            { label: "Workshop",       value: "workshop"   },
            { label: "Seminar",        value: "seminar"    },
            { label: "Pitch Night",    value: "pitch"      },
            { label: "Award Ceremony", value: "awards"     },
          ],
        },
        {
          id: "industry",
          label: "Industry",
          type: "toggle",
          options: [
            { label: "Tech",       value: "tech"       },
            { label: "F&B",        value: "fnb"        },
            { label: "Finance",    value: "finance"    },
            { label: "Healthcare", value: "healthcare" },
            { label: "Education",  value: "education"  },
            { label: "General",    value: "general"    },
          ],
        },
        {
          id: "event_format",
          label: "Format",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "In-person", value: "inperson" },
            { label: "Online",    value: "online"   },
            { label: "Hybrid",    value: "hybrid"   },
          ],
        },
      ],
    },
    {
      id: "financial_services",
      label: "Financial Services",
      icon: "landmark",
      filters: [
        {
          id: "fin_type",
          label: "Service",
          type: "toggle",
          options: [
            { label: "Business Loan",     value: "loan"       },
            { label: "Invoice Financing", value: "invoice"    },
            { label: "Trade Finance",     value: "trade"      },
            { label: "Equity Funding",    value: "equity"     },
            { label: "Grants",            value: "grants"     },
            { label: "Insurance",         value: "insurance"  },
            { label: "Accounting & Tax",  value: "accounting" },
            { label: "Payroll",           value: "payroll"    },
          ],
        },
        {
          id: "provider",
          label: "Provider",
          type: "toggle",
          options: [
            { label: "Bank",         value: "bank"       },
            { label: "VC",           value: "vc"         },
            { label: "Angel",        value: "angel"      },
            { label: "Government",   value: "government" },
            { label: "Private Firm", value: "private"    },
          ],
        },
        {
          id: "for_stage",
          label: "For",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Startup",    value: "startup"    },
            { label: "SME",        value: "sme"        },
            { label: "Enterprise", value: "enterprise" },
          ],
        },
      ],
    },
    {
      id: "biz_misc",
      label: "Miscellaneous",
      icon: "box",
      filters: [
        {
          id: "biz_misc_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Signage & Branding", value: "signage"  },
            { label: "Licenses & Permits", value: "licenses" },
            { label: "Office Space",       value: "office"   },
            { label: "Business Contacts",  value: "contacts" },
            { label: "Other",              value: "other"    },
          ],
        },
        {
          id: "biz_misc_action",
          label: "Action",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "For Sale", value: "sale"     },
            { label: "For Rent", value: "rent"     },
            { label: "Offering", value: "offering" },
            { label: "Wanted",   value: "wanted"   },
          ],
        },
      ],
    },
    {
      id: "wanted",
      label: "Wanted",
      icon: "search",
      filters: [
        {
          id: "biz_looking_for",
          label: "Looking For",
          type: "toggle",
          options: [
            { label: "Business to Buy / Lease", value: "biz_sale"  },
            { label: "B2B Service",             value: "b2b"       },
            { label: "Freelancer / Contractor", value: "freelance" },
            { label: "Partner",                 value: "partner"   },
            { label: "Equipment",               value: "equipment" },
            { label: "Startup Support",         value: "startup"   },
            { label: "Training",                value: "training"  },
            { label: "Franchise",               value: "franchise" },
            { label: "Financial Services",      value: "finance"   },
            { label: "Other",                   value: "other"     },
          ],
        },
        {
          id: "industry",
          label: "Industry",
          type: "toggle",
          options: [
            { label: "Tech",          value: "tech"          },
            { label: "F&B",           value: "fnb"           },
            { label: "Retail",        value: "retail"        },
            { label: "Services",      value: "services"      },
            { label: "Manufacturing", value: "manufacturing"  },
            { label: "Healthcare",    value: "healthcare"    },
            { label: "Education",     value: "education"     },
            { label: "Finance",       value: "finance"       },
            { label: "Other",         value: "other"         },
          ],
        },
      ],
    },
  ],
};
