import type { MainCategory } from "../types";

export const community: MainCategory = {
  id: "community",
  label: "Community",
  description: "Connect through local events and activities.",
  icon: "users",
  iconBg: "bg-emerald-100",
  iconColor: "text-emerald-600",
  subcategories: [
    {
      id: "lost_found",
      label: "Lost & Found",
      icon: "search",
      filters: [
        {
          id: "lf_status",
          label: "Status",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Lost",  value: "lost"  },
            { label: "Found", value: "found" },
          ],
        },
        {
          id: "item_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Pet",          value: "pet"         },
            { label: "Documents",    value: "documents"   },
            { label: "Electronics",  value: "electronics" },
            { label: "Keys",         value: "keys"        },
            { label: "Bag / Wallet", value: "bag"         },
            { label: "Jewellery",    value: "jewellery"   },
            { label: "Clothing",     value: "clothing"    },
            { label: "Vehicle",      value: "vehicle"     },
            { label: "Other",        value: "other"       },
          ],
        },
      ],
    },
    {
      id: "events",
      label: "Events",
      icon: "calendar",
      filters: [
        {
          id: "event_type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Music & Concerts",  value: "music"      },
            { label: "Sports & Fitness",  value: "sports"     },
            { label: "Food & Drinks",     value: "food"       },
            { label: "Arts & Culture",    value: "arts"       },
            { label: "Health & Wellness", value: "wellness"   },
            { label: "Kids & Family",     value: "family"     },
            { label: "Networking",        value: "networking" },
            { label: "Comedy & Theatre",  value: "comedy"     },
            { label: "Community",         value: "community"  },
            { label: "Other",             value: "other"      },
          ],
        },
        {
          id: "event_cost",
          label: "Cost",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",  value: "any"  },
            { label: "Free", value: "free" },
            { label: "Paid", value: "paid" },
          ],
        },
        {
          id: "event_format",
          label: "Format",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "In-person", value: "inperson" },
            { label: "Online",    value: "online"   },
            { label: "Hybrid",    value: "hybrid"   },
          ],
        },
        {
          id: "age_suitability",
          label: "Suitable For",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "All Ages",        value: "all"    },
            { label: "Family-Friendly", value: "family" },
            { label: "Adults Only",     value: "adults" },
            { label: "Kids & Teens",    value: "kids"   },
          ],
        },
      ],
    },
    {
      id: "volunteering",
      label: "Volunteering & Charity",
      icon: "heart",
      filters: [
        {
          id: "cause",
          label: "Cause",
          type: "toggle",
          options: [
            { label: "Environment",     value: "environment" },
            { label: "Animal Welfare",  value: "animal"      },
            { label: "Education",       value: "education"   },
            { label: "Healthcare",      value: "healthcare"  },
            { label: "Elderly Care",    value: "elderly"     },
            { label: "Children",        value: "children"    },
            { label: "Disaster Relief", value: "disaster"    },
            { label: "Poverty",         value: "poverty"     },
            { label: "Other",           value: "other"       },
          ],
        },
        {
          id: "commitment",
          label: "Commitment",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",       value: "any"       },
            { label: "One-time",  value: "once"      },
            { label: "Recurring", value: "recurring" },
          ],
        },
        {
          id: "skills_needed",
          label: "Skills",
          type: "toggle",
          options: [
            { label: "No Skills Needed", value: "none"     },
            { label: "Teaching",         value: "teaching" },
            { label: "Tech",             value: "tech"     },
            { label: "Medical",          value: "medical"  },
            { label: "Cooking",          value: "cooking"  },
            { label: "Driving",          value: "driving"  },
            { label: "Admin",            value: "admin"    },
          ],
        },
        {
          id: "vol_format",
          label: "Format",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",       value: "any"      },
            { label: "In-person", value: "inperson" },
            { label: "Online",    value: "online"   },
          ],
        },
      ],
    },
    {
      id: "announcement",
      label: "Announcement",
      icon: "megaphone",
      filters: [
        {
          id: "ann_type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Community Notice", value: "community"  },
            { label: "Government",       value: "government" },
            { label: "Emergency",        value: "emergency"  },
            { label: "Road & Traffic",   value: "road"       },
            { label: "Infrastructure",   value: "infra"      },
            { label: "Event Notice",     value: "event"      },
            { label: "General",          value: "general"    },
          ],
        },
        {
          id: "ann_from",
          label: "From",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Community Member", value: "member"    },
            { label: "Local Authority",  value: "authority" },
            { label: "NGO",              value: "ngo"       },
            { label: "Business",         value: "business"  },
          ],
        },
        {
          id: "urgency",
          label: "Urgency",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Normal",   value: "normal"   },
            { label: "Urgent",   value: "urgent"   },
            { label: "Critical", value: "critical" },
          ],
        },
      ],
    },
    {
      id: "child_family",
      label: "Child & Family Activities",
      icon: "baby",
      filters: [
        {
          id: "activity_type",
          label: "Activity",
          type: "toggle",
          options: [
            { label: "Playdate",       value: "playdate"    },
            { label: "Classes",        value: "classes"     },
            { label: "Sports",         value: "sports"      },
            { label: "Arts & Crafts",  value: "arts"        },
            { label: "Educational",    value: "educational" },
            { label: "Camps",          value: "camps"       },
            { label: "Cultural",       value: "cultural"    },
            { label: "Birthday Party", value: "birthday"    },
            { label: "Other",          value: "other"       },
          ],
        },
        {
          id: "age_group",
          label: "Age Group",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "0-2 yrs",   value: "baby"   },
            { label: "3-5 yrs",   value: "3to5"   },
            { label: "6-9 yrs",   value: "6to9"   },
            { label: "10-12 yrs", value: "10to12" },
            { label: "13-17 yrs", value: "teen"   },
          ],
        },
        {
          id: "activity_cost",
          label: "Cost",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Free", value: "free" },
            { label: "Paid", value: "paid" },
          ],
        },
        {
          id: "activity_format",
          label: "Format",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "In-person", value: "inperson" },
            { label: "Online",    value: "online"   },
          ],
        },
      ],
    },
    {
      id: "general_others",
      label: "General / Others",
      icon: "circle-ellipsis",
      filters: [
        {
          id: "gen_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Tips & Advice",   value: "tips"          },
            { label: "Neighbourhood",   value: "neighbourhood" },
            { label: "Local Services",  value: "services"      },
            { label: "Charity",         value: "charity"       },
            { label: "Swap / Exchange", value: "swap"          },
            { label: "Other",           value: "other"         },
          ],
        },
        {
          id: "gen_action",
          label: "Action",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Sharing Info", value: "sharing"  },
            { label: "Asking Help",  value: "asking"   },
            { label: "Offering",     value: "offering" },
          ],
        },
      ],
    },
    {
      id: "rideshare_carpool",
      label: "Rideshare & Carpool",
      icon: "car",
      filters: [
        {
          id: "route_type",
          label: "Route",
          type: "toggle",
          options: [
            { label: "Daily Commute",  value: "commute"   },
            { label: "One-way Trip",   value: "oneway"    },
            { label: "Weekend",        value: "weekend"   },
            { label: "Outstation",     value: "outstation" },
          ],
        },
        {
          id: "seats",
          label: "Seats Available",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "1", value: "1" },
            { label: "2", value: "2" },
            { label: "3", value: "3" },
            { label: "4+", value: "4plus" },
          ],
        },
        {
          id: "ride_offer",
          label: "I am",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Offering Ride",  value: "offering" },
            { label: "Looking for Ride", value: "seeking" },
          ],
        },
      ],
    },
  ],
};
