import type { MainCategory } from "../types";

export const electronicsTech: MainCategory = {
  id: "electronics_tech",
  label: "Electronics & Tech",
  description: "Phones, laptops, gaming, cameras, and smart devices.",
  icon: "smartphone",
  iconBg: "bg-red-100",
  iconColor: "text-red-600",
  subcategories: [
    {
      id: "mobile_tablets",
      label: "Mobile Phones & Tablets",
      icon: "smartphone",
      filters: [
        {
          id: "brand",
          label: "Brand",
          type: "toggle",
          options: [
            { label: "Apple",    value: "apple"   },
            { label: "Samsung",  value: "samsung" },
            { label: "Google",   value: "google"  },
            { label: "OnePlus",  value: "oneplus" },
            { label: "Xiaomi",   value: "xiaomi"  },
            { label: "Other",    value: "other"   },
          ],
        },
        {
          id: "storage",
          label: "Storage",
          type: "toggle",
          options: [
            { label: "64GB",  value: "64"  },
            { label: "128GB", value: "128" },
            { label: "256GB", value: "256" },
            { label: "512GB", value: "512" },
            { label: "1TB",   value: "1tb" },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "laptops_computers",
      label: "Laptops & Computers",
      icon: "laptop",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",       value: "any"     },
            { label: "Laptop",    value: "laptop"  },
            { label: "Desktop",   value: "desktop" },
            { label: "All-in-One", value: "aio"   },
            { label: "Mini PC",   value: "mini_pc" },
          ],
        },
        {
          id: "brand",
          label: "Brand",
          type: "toggle",
          options: [
            { label: "Apple",  value: "apple"  },
            { label: "Dell",   value: "dell"   },
            { label: "HP",     value: "hp"     },
            { label: "Lenovo", value: "lenovo" },
            { label: "Asus",   value: "asus"   },
            { label: "Other",  value: "other"  },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "tvs_audio",
      label: "TVs & Audio",
      icon: "monitor",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "TV",           value: "tv"         },
            { label: "Soundbar",     value: "soundbar"   },
            { label: "Speakers",     value: "speakers"   },
            { label: "Headphones",   value: "headphones" },
            { label: "Earbuds",      value: "earbuds"    },
            { label: "Home Cinema",  value: "cinema"     },
          ],
        },
        {
          id: "screen_size",
          label: "Screen Size",
          type: "toggle",
          options: [
            { label: "Under 32\"", value: "under_32" },
            { label: "32–49\"",    value: "32_49"    },
            { label: "50–65\"",    value: "50_65"    },
            { label: "65\"+",      value: "65plus"   },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "gaming",
      label: "Gaming",
      icon: "gamepad",
      filters: [
        {
          id: "platform",
          label: "Platform",
          type: "toggle",
          options: [
            { label: "PlayStation", value: "ps"      },
            { label: "Xbox",        value: "xbox"    },
            { label: "Nintendo",    value: "nintendo"},
            { label: "PC",          value: "pc"      },
            { label: "Mobile",      value: "mobile"  },
          ],
        },
        {
          id: "item_type",
          label: "Item Type",
          type: "toggle",
          options: [
            { label: "Console",     value: "console"    },
            { label: "Game",        value: "game"       },
            { label: "Controller",  value: "controller" },
            { label: "Accessory",   value: "accessory"  },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "cameras_photography",
      label: "Cameras & Photography",
      icon: "camera",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "DSLR",        value: "dslr"       },
            { label: "Mirrorless",  value: "mirrorless" },
            { label: "Action Cam",  value: "action"     },
            { label: "Drone",       value: "drone"      },
            { label: "Lens",        value: "lens"       },
            { label: "Accessory",   value: "accessory"  },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "computer_parts",
      label: "Computer Parts & Components",
      icon: "cpu",
      filters: [
        {
          id: "type",
          label: "Component",
          type: "toggle",
          options: [
            { label: "GPU",         value: "gpu"         },
            { label: "CPU",         value: "cpu"         },
            { label: "RAM",         value: "ram"         },
            { label: "SSD / HDD",   value: "storage"     },
            { label: "Motherboard", value: "motherboard" },
            { label: "PSU",         value: "psu"         },
            { label: "Other",       value: "other"       },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "wearables_smart",
      label: "Wearables & Smart Devices",
      icon: "watch",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Smartwatch",      value: "smartwatch"  },
            { label: "Fitness Tracker", value: "tracker"     },
            { label: "Smart Speaker",   value: "speaker"     },
            { label: "Smart Display",   value: "display"     },
            { label: "Other",           value: "other"       },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "tech_accessories",
      label: "Tech Accessories",
      icon: "plug",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Cases & Covers", value: "cases"    },
            { label: "Chargers",       value: "chargers" },
            { label: "Cables",         value: "cables"   },
            { label: "Keyboards",      value: "keyboards"},
            { label: "Mice",           value: "mice"     },
            { label: "Other",          value: "other"    },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
          ],
        },
      ],
    },
  ],
};
