import type { MainCategory } from "../types";

export const fashionClothing: MainCategory = {
  id: "fashion_clothing",
  label: "Fashion & Clothing",
  description: "Clothes, shoes, bags, jewellery, and designer finds.",
  icon: "shirt",
  iconBg: "bg-purple-100",
  iconColor: "text-purple-600",
  subcategories: [
    {
      id: "mens_clothing",
      label: "Men's Clothing",
      icon: "shirt",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "T-Shirts & Tops", value: "tops"    },
            { label: "Shirts",          value: "shirts"  },
            { label: "Jeans & Trousers",value: "bottoms" },
            { label: "Jackets & Coats", value: "jackets" },
            { label: "Suits & Formal",  value: "suits"   },
            { label: "Sportswear",      value: "sport"   },
            { label: "Other",           value: "other"   },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",          value: "any"      },
            { label: "New with tags", value: "new_tags" },
            { label: "Like New",      value: "like_new" },
            { label: "Good",          value: "good"     },
            { label: "Fair",          value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "womens_clothing",
      label: "Women's Clothing",
      icon: "shirt",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Tops & Blouses",   value: "tops"    },
            { label: "Dresses",          value: "dresses" },
            { label: "Skirts",           value: "skirts"  },
            { label: "Jeans & Trousers", value: "bottoms" },
            { label: "Jackets & Coats",  value: "jackets" },
            { label: "Activewear",       value: "active"  },
            { label: "Other",            value: "other"   },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",          value: "any"      },
            { label: "New with tags", value: "new_tags" },
            { label: "Like New",      value: "like_new" },
            { label: "Good",          value: "good"     },
            { label: "Fair",          value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "ethnic_traditional",
      label: "Traditional & Ethnic Wear",
      icon: "star",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Saree",           value: "saree"     },
            { label: "Kurta / Salwar",  value: "kurta"     },
            { label: "Lehenga",         value: "lehenga"   },
            { label: "Sherwani",        value: "sherwani"  },
            { label: "Kebaya",          value: "kebaya"    },
            { label: "Cheongsam",       value: "cheongsam" },
            { label: "Other",           value: "other"     },
          ],
        },
        {
          id: "gender",
          label: "Gender",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",   value: "any"   },
            { label: "Women", value: "women" },
            { label: "Men",   value: "men"   },
            { label: "Kids",  value: "kids"  },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",          value: "any"      },
            { label: "New with tags", value: "new_tags" },
            { label: "Like New",      value: "like_new" },
            { label: "Good",          value: "good"     },
            { label: "Fair",          value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "shoes_footwear",
      label: "Shoes & Footwear",
      icon: "footprints",
      filters: [
        {
          id: "gender",
          label: "Gender",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",   value: "any"   },
            { label: "Men",   value: "men"   },
            { label: "Women", value: "women" },
            { label: "Kids",  value: "kids"  },
          ],
        },
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Trainers / Sneakers", value: "trainers" },
            { label: "Boots",               value: "boots"    },
            { label: "Heels",               value: "heels"    },
            { label: "Sandals",             value: "sandals"  },
            { label: "Formal",              value: "formal"   },
            { label: "Slippers",            value: "slippers" },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [            { label: "Any",      value: "any"      },            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "bags_accessories",
      label: "Bags & Accessories",
      icon: "bag",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Handbag",     value: "handbag"    },
            { label: "Backpack",    value: "backpack"   },
            { label: "Wallet",      value: "wallet"     },
            { label: "Belt",        value: "belt"       },
            { label: "Sunglasses",  value: "sunglasses" },
            { label: "Scarf / Hat", value: "scarf"      },
            { label: "Other",       value: "other"      },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "jewellery_watches",
      label: "Jewellery & Watches",
      icon: "gem",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Necklace",   value: "necklace"  },
            { label: "Earrings",   value: "earrings"  },
            { label: "Bracelet",   value: "bracelet"  },
            { label: "Ring",       value: "ring"      },
            { label: "Watch",      value: "watch"     },
            { label: "Gold",       value: "gold"      },
            { label: "Other",      value: "other"     },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "designer_luxury",
      label: "Designer & Luxury",
      icon: "crown",
      filters: [
        {
          id: "brand_tier",
          label: "Brand",
          type: "toggle",
          options: [
            { label: "Louis Vuitton", value: "lv"       },
            { label: "Gucci",         value: "gucci"    },
            { label: "Prada",         value: "prada"    },
            { label: "Chanel",        value: "chanel"   },
            { label: "Hermès",        value: "hermes"   },
            { label: "Other Luxury",  value: "other"    },
          ],
        },
        {
          id: "category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Bag",       value: "bag"      },
            { label: "Watch",     value: "watch"    },
            { label: "Shoes",     value: "shoes"    },
            { label: "Clothing",  value: "clothing" },
            { label: "Jewellery", value: "jewellery"},
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "New",             value: "new"      },
            { label: "Excellent",       value: "excellent"},
            { label: "Good",            value: "good"     },
            { label: "Signs of Wear",   value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "vintage_secondhand",
      label: "Vintage & Preloved",
      icon: "recycle",
      filters: [
        {
          id: "decade",
          label: "Era",
          type: "toggle",
          options: [
            { label: "60s / 70s", value: "60s_70s" },
            { label: "80s",       value: "80s"     },
            { label: "90s",       value: "90s"     },
            { label: "Y2K",       value: "y2k"     },
          ],
        },
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Clothing",    value: "clothing"    },
            { label: "Shoes",       value: "shoes"       },
            { label: "Accessories", value: "accessories" },
            { label: "Jewellery",   value: "jewellery"   },
          ],
        },
      ],
    },
  ],
};
