import type { MainCategory } from "../types";

export const homeFurniture: MainCategory = {
  id: "home_furniture",
  label: "Home & Furniture",
  description: "Sofas, appliances, garden gear, décor, and DIY tools.",
  icon: "sofa",
  iconBg: "bg-stone-100",
  iconColor: "text-stone-600",
  subcategories: [
    {
      id: "sofas_seating",
      label: "Sofas & Seating",
      icon: "armchair",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Sofa",       value: "sofa"       },
            { label: "Armchair",   value: "armchair"   },
            { label: "Ottoman",    value: "ottoman"    },
            { label: "Sofa Bed",   value: "sofa_bed"   },
            { label: "Bench",      value: "bench"      },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "beds_bedroom",
      label: "Beds & Bedroom",
      icon: "bed",
      filters: [
        {
          id: "bed_size",
          label: "Bed Size",
          type: "toggle",
          options: [
            { label: "Single",     value: "single"     },
            { label: "Double",     value: "double"     },
            { label: "King",       value: "king"       },
            { label: "Super King", value: "super_king" },
          ],
        },
        {
          id: "item_type",
          label: "Item Type",
          type: "toggle",
          options: [
            { label: "Bed Frame",   value: "bed_frame"   },
            { label: "Mattress",    value: "mattress"    },
            { label: "Wardrobe",    value: "wardrobe"    },
            { label: "Chest / Drawers", value: "drawers" },
            { label: "Bedside Table", value: "bedside"   },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "tables_dining",
      label: "Tables, Desks & Dining",
      icon: "table",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Dining Table", value: "dining"  },
            { label: "Desk",         value: "desk"    },
            { label: "Coffee Table", value: "coffee"  },
            { label: "Side Table",   value: "side"    },
            { label: "Dining Chair", value: "chair"   },
            { label: "Office Chair", value: "office_chair" },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "kitchen_appliances",
      label: "Kitchen & Appliances",
      icon: "microwave",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Fridge / Freezer",     value: "fridge"      },
            { label: "Washing Machine",       value: "washing"     },
            { label: "Dishwasher",            value: "dishwasher"  },
            { label: "Microwave / Oven",      value: "microwave"   },
            { label: "Hob / Cooker",          value: "cooker"      },
            { label: "Vacuum / Air Purifier", value: "vacuum"      },
            { label: "Small Appliances",      value: "small"       },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "storage_shelving",
      label: "Storage & Shelving",
      icon: "archive",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Bookcase / Shelf", value: "shelf"     },
            { label: "Cabinet",          value: "cabinet"   },
            { label: "Storage Box",      value: "box"       },
            { label: "Rack",             value: "rack"      },
            { label: "Cubby / Cube Unit",value: "cube"      },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "home_decor",
      label: "Home Décor & Accessories",
      icon: "sparkles",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Rugs & Carpets",    value: "rugs"      },
            { label: "Curtains & Blinds", value: "curtains"  },
            { label: "Wall Art",          value: "art"       },
            { label: "Mirrors",           value: "mirrors"   },
            { label: "Cushions & Throws", value: "cushions"  },
            { label: "Lighting",          value: "lighting"  },
            { label: "Plants & Pots",     value: "plants"    },
            { label: "Other",             value: "other"     },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "garden_outdoor",
      label: "Garden & Outdoor",
      icon: "tree",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Garden Furniture", value: "furniture" },
            { label: "BBQ & Grills",     value: "bbq"       },
            { label: "Gardening Tools",  value: "tools"     },
            { label: "Plants & Seeds",   value: "plants"    },
            { label: "Pots & Planters",  value: "pots"      },
            { label: "Decking / Fencing",value: "decking"   },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
    {
      id: "diy_tools",
      label: "DIY, Tools & Hardware",
      icon: "wrench",
      filters: [
        {
          id: "type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Power Tools",  value: "power"    },
            { label: "Hand Tools",   value: "hand"     },
            { label: "Plumbing",     value: "plumbing" },
            { label: "Electrical",   value: "electric" },
            { label: "Flooring",     value: "flooring" },
            { label: "Paint",        value: "paint"    },
            { label: "Other",        value: "other"    },
          ],
        },
        {
          id: "condition",
          label: "Condition",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Any",      value: "any"      },
            { label: "New",      value: "new"      },
            { label: "Like New", value: "like_new" },
            { label: "Good",     value: "good"     },
            { label: "Fair",     value: "fair"     },
          ],
        },
      ],
    },
  ],
};
