import type { MainCategory } from "../types";
import { discount, dealType, redemption } from "./shared";

export const specialOffers: MainCategory = {
  id: "special_offers",
  label: "Special Offers",
  description: "Exclusive deals, discounts, and limited-time offers.",
  icon: "tag",
  iconBg: "bg-rose-100",
  iconColor: "text-rose-600",
  subcategories: [
    {
      id: "banking_finance",
      label: "Banking & Finance",
      icon: "landmark",
      filters: [
        {
          id: "bf_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Credit Card", value: "credit_card" },
            { label: "Loan",        value: "loan"        },
            { label: "Insurance",   value: "insurance"   },
            { label: "Savings",     value: "savings"     },
            { label: "Investment",  value: "investment"  },
            { label: "Other",       value: "other"       },
          ],
        },
        dealType,
        discount,
      ],
    },
    {
      id: "travel_tourism",
      label: "Travel & Tourism",
      icon: "plane",
      filters: [
        {
          id: "travel_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Flights",    value: "flights"    },
            { label: "Hotels",     value: "hotels"     },
            { label: "Packages",   value: "packages"   },
            { label: "Activities", value: "activities" },
            { label: "Car Rental", value: "car_rental" },
          ],
        },
        dealType,
        discount,
      ],
    },
    {
      id: "retail_shopping",
      label: "Retail & Shopping",
      icon: "shopping-bag",
      filters: [
        {
          id: "shop_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Fashion",       value: "fashion"     },
            { label: "Electronics",   value: "electronics" },
            { label: "Home & Living", value: "home"        },
            { label: "Beauty",        value: "beauty"      },
            { label: "Sports",        value: "sports"      },
            { label: "Kids",          value: "kids"        },
            { label: "Groceries",     value: "groceries"   },
            { label: "Other",         value: "other"       },
          ],
        },
        dealType,
        redemption,
        discount,
      ],
    },
    {
      id: "food_dining",
      label: "Food & Dining",
      icon: "utensils-crossed",
      filters: [
        {
          id: "cuisine",
          label: "Cuisine",
          type: "toggle",
          options: [
            { label: "Local",     value: "local"     },
            { label: "Asian",     value: "asian"     },
            { label: "Western",   value: "western"   },
            { label: "Fusion",    value: "fusion"    },
            { label: "Fast Food", value: "fast_food" },
            { label: "Café",      value: "cafe"      },
            { label: "Buffet",    value: "buffet"    },
          ],
        },
        {
          id: "meal_type",
          label: "Meal Type",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "Dine-in",  value: "dinein"   },
            { label: "Takeaway", value: "takeaway" },
            { label: "Delivery", value: "delivery" },
          ],
        },
        dealType,
        discount,
      ],
    },
    {
      id: "electronics_gadgets",
      label: "Electronics & Gadgets",
      icon: "monitor",
      filters: [
        {
          id: "elec_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Phone",      value: "phone"      },
            { label: "Laptop",     value: "laptop"     },
            { label: "TV",         value: "tv"         },
            { label: "Camera",     value: "camera"     },
            { label: "Gaming",     value: "gaming"     },
            { label: "Smart Home", value: "smart_home" },
            { label: "Audio",      value: "audio"      },
            { label: "Wearable",   value: "wearable"   },
          ],
        },
        {
          id: "elec_deal_type",
          label: "Deal Type",
          type: "toggle",
          options: [
            { label: "% Off",             value: "pct_off"  },
            { label: "Bundle",            value: "bundle"   },
            { label: "Trade-in",          value: "tradein"  },
            { label: "Flash Sale",        value: "flash"    },
            { label: "Extended Warranty", value: "warranty" },
            { label: "Voucher",           value: "voucher"  },
          ],
        },
        redemption,
        discount,
      ],
    },
    {
      id: "health_wellness",
      label: "Health & Wellness",
      icon: "heart-pulse",
      filters: [
        {
          id: "hw_type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Gym",           value: "gym"          },
            { label: "Spa & Massage", value: "spa"          },
            { label: "Salon",         value: "salon"        },
            { label: "Dental",        value: "dental"       },
            { label: "Optical",       value: "optical"      },
            { label: "Pharmacy",      value: "pharmacy"     },
            { label: "Medical",       value: "medical"      },
            { label: "Mental Health", value: "mental_health"},
          ],
        },
        dealType,
        redemption,
        discount,
      ],
    },
    {
      id: "education_learning",
      label: "Education & Learning",
      icon: "graduation-cap",
      filters: [
        {
          id: "edu_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Languages",      value: "languages"    },
            { label: "Tech & Coding",  value: "tech"         },
            { label: "Arts & Music",   value: "arts"         },
            { label: "Professional",   value: "professional" },
            { label: "Kids Programs",  value: "kids"         },
            { label: "Online Courses", value: "online"       },
            { label: "Test Prep",      value: "test_prep"    },
          ],
        },
        {
          id: "edu_format",
          label: "Format",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "In-person", value: "inperson" },
            { label: "Online",    value: "online"   },
            { label: "Hybrid",    value: "hybrid"   },
          ],
        },
        dealType,
        discount,
      ],
    },
    {
      id: "holiday_seasonal",
      label: "Holiday & Seasonal Offers",
      icon: "sparkles",
      filters: [
        {
          id: "occasion",
          label: "Occasion",
          type: "toggle",
          options: [
            { label: "Chinese New Year", value: "cny"          },
            { label: "Eid / Raya",       value: "eid"          },
            { label: "Christmas",        value: "christmas"    },
            { label: "Diwali",           value: "diwali"       },
            { label: "Mid-Year Sale",    value: "midyear"      },
            { label: "Year-End Sale",    value: "yearend"      },
            { label: "National Day",     value: "national"     },
            { label: "Valentine's",      value: "valentines"   },
            { label: "Back to School",   value: "backtoschool" },
          ],
        },
        {
          id: "seasonal_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Travel",        value: "travel"       },
            { label: "Shopping",      value: "shopping"     },
            { label: "Dining",        value: "dining"       },
            { label: "Entertainment", value: "entertainment" },
            { label: "Home",          value: "home"         },
            { label: "Gifts",         value: "gifts"        },
          ],
        },
        discount,
      ],
    },
    {
      id: "entertainment",
      label: "Entertainment",
      icon: "ticket",
      filters: [
        {
          id: "ent_type",
          label: "Type",
          type: "toggle",
          options: [
            { label: "Movies",        value: "movies"      },
            { label: "Theme Parks",   value: "theme_parks" },
            { label: "Sports Events", value: "sports"      },
            { label: "Concerts",      value: "concerts"    },
            { label: "Gaming",        value: "gaming"      },
            { label: "Museum",        value: "museum"      },
            { label: "Escape Room",   value: "escape_room" },
            { label: "Streaming",     value: "streaming"   },
          ],
        },
        {
          id: "ent_format",
          label: "Format",
          type: "toggle",
          singleSelect: true,
          options: [
            { label: "In-person", value: "inperson" },
            { label: "Online",    value: "online"   },
          ],
        },
        dealType,
        discount,
      ],
    },
    {
      id: "home_living",
      label: "Home & Living",
      icon: "armchair",
      filters: [
        {
          id: "home_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Furniture",   value: "furniture"  },
            { label: "Appliances",  value: "appliances" },
            { label: "Renovation",  value: "renovation" },
            { label: "Cleaning",    value: "cleaning"   },
            { label: "Decor",       value: "decor"      },
            { label: "Gardening",   value: "gardening"  },
            { label: "Smart Home",  value: "smart_home" },
            { label: "Bedding",     value: "bedding"    },
          ],
        },
        dealType,
        redemption,
        discount,
      ],
    },
    {
      id: "automotive",
      label: "Automotive",
      icon: "car",
      filters: [
        {
          id: "auto_type",
          label: "Service",
          type: "toggle",
          options: [
            { label: "Workshop",    value: "workshop"    },
            { label: "Car Wash",    value: "wash"        },
            { label: "Tyre & Rim",  value: "tyre"        },
            { label: "Insurance",   value: "insurance"   },
            { label: "Accessories", value: "accessories" },
            { label: "Grooming",    value: "grooming"    },
            { label: "EV Charging", value: "ev_charging" },
          ],
        },
        {
          id: "for_vehicle",
          label: "For Vehicle",
          type: "toggle",
          options: [
            { label: "Car",        value: "car"        },
            { label: "Motorcycle", value: "motorcycle" },
            { label: "Van",        value: "van"        },
            { label: "Truck",      value: "truck"      },
          ],
        },
        discount,
      ],
    },
    {
      id: "misc_offers",
      label: "Miscellaneous",
      icon: "box",
      filters: [
        {
          id: "misc_offer_category",
          label: "Category",
          type: "toggle",
          options: [
            { label: "Pet Care",      value: "pet_care"     },
            { label: "Printing",      value: "printing"     },
            { label: "Photography",   value: "photography"  },
            { label: "Gifts",         value: "gifts"        },
            { label: "Subscriptions", value: "subscription" },
            { label: "Other",         value: "other"        },
          ],
        },
        dealType,
        redemption,
        discount,
      ],
    },
  ],
};
